language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot"

notifications:
  email: false
